[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "gabs-vieira"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "easyocr (>=1.7.2,<2.0.0)"
]

[tool.poetry]
packages = [{include = "backend", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
